### ISSUE TITLE
supplement

### ISSUE THREAD

**Issue by micky-li-hd** [ZhenyuSun-Walker/Awesome-Text-to-3D-Plus#1]
LucidDreamer is also an excellent work which is CVPR2024 spotlight by Yingcong Chen.
Recommend it!

**Comment by ZhenyuSun-Walker** [comment]
Thank you for the recommendation! I will definitely check out ‘LucidDreamer’ by Yingcong Chen, especially since it’s a CVPR2024 spotlight work.

**Comment by ZhenyuSun-Walker** [comment]
I just found [this work](https://github.com/EnVision-Research/LucidDreamer), actually it won the CVPR 2024 Highlight (11.9%). But that doesn’t take away from the fact that it’s an excellent piece of work. I'll add it to my collection.
